# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CASCAIDE Bid
author: Michael Allen
logo: logo.png

#only build files specified in table of contents file
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off' # force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/MichaelAllen1966/cascaide_bid/  # Online location of your book
